name: Render Manim Videos

on:
  push:
    branches:
      - presentation

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: presentation

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull Manim Docker image
      run: docker pull manimcommunity/manim:stable

    - name: Render videos with Manim
      run: |
        docker run --rm -v ${{ github.workspace }}:/manim manimcommunity/manim:stable manim -pqk scenes.py SolarAngleScene

    - name: Upload rendered videos as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rendered-videos
        path: media/video/scenes/2160p60/SolarAngleScene.mp4
